In [16]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier #决策树分类
from sklearn.tree import DecisionTreeRegressor #决策树回归
import matplotlib.pyplot as plt
%matplotlib inline
path = r"./lenses.txt"
data = pd.read_table(path, header=None)
data

             0      1    2        3          4
0        young  myope   no  reduced  no lenses
1        young  myope   no   normal       soft
2        young  myope  yes  reduced  no lenses
3        young  myope  yes   normal       hard
4        young  hyper   no  reduced  no lenses
5        young  hyper   no   normal       soft
6        young  hyper  yes  reduced  no lenses
7        young  hyper  yes   normal       hard
8          pre  myope   no  reduced  no lenses
9          pre  myope   no   normal       soft
10         pre  myope  yes  reduced  no lenses
11         pre  myope  yes   normal       hard
12         pre  hyper   no  reduced  no lenses
13         pre  hyper   no   normal       soft
14         pre  hyper  yes  reduced  no lenses
15         pre  hyper  yes   normal  no lenses
16  presbyopic  myope   no  reduced  no lenses
17  presbyopic  myope   no   normal  no lenses
18  presbyopic  myope  yes  reduced  no lenses
19  presbyopic  myope  yes   normal       hard
20  presbyopic  hyper   no  reduced  no lenses
21  presbyopic  hyper   no   normal       soft
22  presbyopic  hyper  yes  reduced  no lenses
23  presbyopic  hyper  yes   normal  no lenses

In [17]:
data[0].unique()

array(['young', 'pre', 'presbyopic'], dtype=object)

In [18]:
data[1].unique()

array(['myope', 'hyper'], dtype=object)

In [19]:
data[3].unique() #看对应的列不重合的数据是哪些

array(['reduced', 'normal'], dtype=object)

In [20]:
dict0 = {"young":0, "pre":1, "presbyopic":2} #这里是手动把每列那些不重复的值映射为数字
data[0] = data[0].map(dict0)
data[0]

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    2
17    2
18    2
19    2
20    2
21    2
22    2
23    2
Name: 0, dtype: int64

In [21]:
dict1 = {"myope":0, "hyper":1}
data[1] = data[1].map(dict1)
data[1]

0     0
1     0
2     0
3     0
4     1
5     1
6     1
7     1
8     0
9     0
10    0
11    0
12    1
13    1
14    1
15    1
16    0
17    0
18    0
19    0
20    1
21    1
22    1
23    1
Name: 1, dtype: int64

In [22]:
dict2 = {"yes":0, "no":1}
data[2] = data[2].map(dict2)
data[2]

0     1
1     1
2     0
3     0
4     1
5     1
6     0
7     0
8     1
9     1
10    0
11    0
12    1
13    1
14    0
15    0
16    1
17    1
18    0
19    0
20    1
21    1
22    0
23    0
Name: 2, dtype: int64

In [23]:
dict3 = {"reduced":0, "normal":1}
data[3] = data[3].map(dict3)
data[3]

0     0
1     1
2     0
3     1
4     0
5     1
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
16    0
17    1
18    0
19    1
20    0
21    1
22    0
23    1
Name: 3, dtype: int64

In [24]:
dict4 = {"no lenses":0, "soft":1, "hard":2}
data[4] = data[4].map(dict4)
data[4]

0     0
1     1
2     0
3     2
4     0
5     1
6     0
7     2
8     0
9     1
10    0
11    2
12    0
13    1
14    0
15    0
16    0
17    0
18    0
19    2
20    0
21    1
22    0
23    0
Name: 4, dtype: int64

In [25]:
data

    0  1  2  3  4
0   0  0  1  0  0
1   0  0  1  1  1
2   0  0  0  0  0
3   0  0  0  1  2
4   0  1  1  0  0
5   0  1  1  1  1
6   0  1  0  0  0
7   0  1  0  1  2
8   1  0  1  0  0
9   1  0  1  1  1
10  1  0  0  0  0
11  1  0  0  1  2
12  1  1  1  0  0
13  1  1  1  1  1
14  1  1  0  0  0
15  1  1  0  1  0
16  2  0  1  0  0
17  2  0  1  1  0
18  2  0  0  0  0
19  2  0  0  1  2
20  2  1  1  0  0
21  2  1  1  1  1
22  2  1  0  0  0
23  2  1  0  1  0

In [27]:
x_train, x_test = data.iloc[:-2, :-1], data.iloc[-2:, :-1] #创建决策树分类
y_train, y_test = data[4][:-2], data[4][-2:] #训练数据

In [28]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [29]:
y_new = dtc.predict(x_test)
y_new

array([0, 0], dtype=int64)

In [30]:
y_test

22    0
23    0
Name: 4, dtype: int64

In [31]:
y_test.ravel() #表示将数据旋转一下

array([0, 0], dtype=int64)