In [1]:
# 数据预览
import pandas as pd
datapath = "air_data.csv"
data = pd.read_csv(datapath, encoding="utf-8")
print(data)

       MEMBER_NO    FFP_DATE FIRST_FLIGHT_DATE GENDER  FFP_TIER  \
0          54993  2006/11/02        2008/12/24      男         6
1          28065  2007/02/19        2007/08/03      男         6
2          55106  2007/02/01        2007/08/30      男         6
3          21189  2008/08/22        2008/08/23      男         5
4          39546  2009/04/10        2009/04/15      男         6
5          56972  2008/02/10        2009/09/29      男         6
6          44924  2006/03/22        2006/03/29      男         6
7          22631  2010/04/09        2010/04/09      女         6
8          32197  2011/06/07        2011/07/01      男         5
9          31645  2010/07/05        2010/07/05      女         6
10         58877  2010/11/18        2010/11/20      女         6
11         37994  2004/11/13        2004/12/02      男         6
12         28012  2006/11/23        2007/11/18      男         5
13         54943  2006/10/25        2007/10/27      男         6
14         57881  2010/02/01        2010/02/01      女         6
15          1254  2008/03/28        2008/04/05      男         4
16          8253  2010/07/15        2010/08/20      男         6
17         58899  2010/11/10        2011/02/23      女         6
18         26955  2006/04/06        2007/02/22      男         6
19         41616  2011/08/29        2011/10/22      男         6
20         21501  2008/07/30        2008/11/21      男         6
21         41281  2011/06/07        2011/06/09      男         6
22         47229  2005/04/10        2005/04/10      男         6
23         28474  2010/04/13        2010/04/13      男         6
24         58472  2010/02/14        2010/03/01      女         5
25         13942  2010/10/14        2010/11/01      男         6
26         45075  2007/02/01        2007/03/23      男         6
27         47114  2005/01/15        2005/03/17      男         6
28         54619  2006/01/07        2006/01/08      男         6
29         12349  2008/06/16        2008/06/27      男         6
...          ...         ...               ...    ...       ...
62958      52412  2013/02/22        2013/02/22      男         4
62959      47026  2013/03/03        2013/07/28      男         4
62960      11699  2008/02/13        2013/07/15      女         4
62961       3305  2009/12/12        2009/12/13      男         4
62962       5515  2011/07/17        2011/07/17      男         4
62963      10999  2004/12/16        2004/12/18      女         4
62964      34341  2013/01/31        2013/01/31      男         4
62965      57428  2008/12/05        2008/12/05      女         4
62966      60676  2012/07/12        2013/02/08      男         4
62967        359  2012/04/12        2012/05/30      男         4
62968       1405  2010/07/07        2010/09/24      男         4
62969      25238  2012/10/23        2012/10/23      女         4
62970      38088  2005/03/11        2005/06/16      女         4
62971      45524  2013/02/12        2013/04/03      女         4
62972        197  2011/01/14        2013/09/26      男         4
62973       7445  2013/03/29        2013/04/06      男         4
62974      11163  2005/05/08        2005/08/26      男         4
62975      30765  2008/11/16        2013/11/30      男         4
62976      10380  2010/07/08        2011/06/21      男         4
62977      16372  2012/12/20        2012/12/20      男         4
62978      22761  2011/04/14        2011/04/14      男         4
62979      34330  2013/03/16        2013/03/17      男         4
62980       1761  2012/08/07        2012/09/09      女         4
62981      15206  2011/12/02        2011/12/02      女         4
62982      16415  2013/01/20        2013/01/20      女         4
62983      18375  2011/05/20        2013/06/05      女         4
62984      36041  2010/03/08        2013/09/14      男         4
62985      45690  2006/03/30        2006/12/02      女         4
62986      61027  2013/02/06        2013/02/14      女         4
62987      61340  2013/02/17        2013/02/17      女         4

             WORK_CITY WORK_PROVINCE WORK_COUNTRY   AGE   LOAD_TIME  \
0                    .            北京           CN  31.0  2014/03/31
1                  NaN            北京           CN  42.0  2014/03/31
2                    .            北京           CN  40.0  2014/03/31
3          Los Angeles            CA           US  64.0  2014/03/31
4                   贵阳            贵州           CN  48.0  2014/03/31
5                   广州            广东           CN  64.0  2014/03/31
6                乌鲁木齐市            新疆           CN  46.0  2014/03/31
7                  温州市            浙江           CN  50.0  2014/03/31
8               DRANCY           NaN           FR  50.0  2014/03/31
9                   温州            浙江           CN  43.0  2014/03/31
10               PARIS         PARIS           FR  34.0  2014/03/31
11                  北京             .           CN  47.0  2014/03/31
12          SAN MARINO            CA           US  58.0  2014/03/31
13                  深圳            广东           CN  47.0  2014/03/31
14                  广州            广东           CN  45.0  2014/03/31
15     BOWLAND HEIGHTS    CALIFORNIA           US  63.0  2014/03/31
16                乌鲁木齐            新疆           CN  48.0  2014/03/31
17               PARIS           NaN           FR  50.0  2014/03/31
18               乌鲁木齐市            新疆           CN  54.0  2014/03/31
19                  东莞            广东           CN  41.0  2014/03/31
20                   .            北京           CN  49.0  2014/03/31
21              VECHEL  NORD BRABANT           AN   NaN  2014/03/31
22                  广州            广东           CN  69.0  2014/03/31
23                 NaN            CA           US  41.0  2014/03/31
24                 NaN           NaN           FR  48.0  2014/03/31
25               PARIS        FRANCE           FR  39.0  2014/03/31
26                  湛江            广东           CN  46.0  2014/03/31
27                   .            北京           CN  47.0  2014/03/31
28                  广州            广东           CN  62.0  2014/03/31
29                  深圳            广东           CN  46.0  2014/03/31
...                ...           ...          ...   ...         ...
62958               台北           NaN           TW  24.0  2014/03/31
62959               化州            广东           CN  25.0  2014/03/31
62960               南宁            广西           CN  73.0  2014/03/31
62961               陵水            海南           CN  46.0  2014/03/31
62962               广州            广东           CN  31.0  2014/03/31
62963              南海市           广东省           CN  60.0  2014/03/31
62964         SURABAYA     JAWATIMUR           ID  40.0  2014/03/31
62965               广州            广东           CN  34.0  2014/03/31
62966           RIYADH           NaN           AA  37.0  2014/03/31
62967              NaN            广东           CN  34.0  2014/03/31
62968               广州            广东           CN  44.0  2014/03/31
62969               广州            广东           CN  39.0  2014/03/31
62970              NaN           NaN           CN  47.0  2014/03/31
62971               广州            广东           CN  29.0  2014/03/31
62972              广州市            广东           CN  36.0  2014/03/31
62973               广州            广东           CN  73.0  2014/03/31
62974              NaN           NaN           CN  34.0  2014/03/31
62975           TAIPEI           NaN           TW  38.0  2014/03/31
62976              贵阳市           贵州省           CN  33.0  2014/03/31
62977               桃园           NaN           TW  47.0  2014/03/31
62978               汕头           广东省           CN  48.0  2014/03/31
62979             乌鲁木齐            新疆           CN  41.0  2014/03/31
62980               深圳            广东           CN  29.0  2014/03/31
62981               广州            广东           CN  42.0  2014/03/31
62982               北京             .           CN  35.0  2014/03/31
62983               广州            广东           CN  25.0  2014/03/31
62984               佛山            广东           CN  38.0  2014/03/31
62985               广州            广东           CN  43.0  2014/03/31
62986               广州            广东           CN  36.0  2014/03/31
62987               上海             .           CN  29.0  2014/03/31

            ...         ADD_Point_SUM  Eli_Add_Point_Sum  L1Y_ELi_Add_Points  \
0           ...                 39992             114452              111100
1           ...                 12000              53288               53288
2           ...                 15491              55202               51711
3           ...                     0              34890               34890
4           ...                 22704              64969               64969
5           ...                  2460              29783               29783
6           ...                 12320              50009               50009
7           ...                  9500              49334               49334
8           ...                   500              32200               32200
9           ...                     0              47052               47052
10          ...                   500              39518               39518
11          ...                 52469              97008               76998
12          ...                     0              35539               35539
13          ...                  2664              29090               26426
14          ...                   400              38428               38028
15          ...                   500              23838               23838
16          ...                 13817              37198               37198
17          ...                     0              31823               31823
18          ...                 12865              34901               34901
19          ...                     0              24656               24656
20          ...                     0              30493               30493
21          ...                  1000              30947               30947
22          ...                 49003              84225               67205
23          ...                     0              24423               24423
24          ...                   500              31138               31138
25          ...                   900              33163               32763
26          ...                556788             577589              384620
27          ...                  5322              25366               22504
28          ...                  3552              28425               24873
29          ...                  1776              24215               22439
...         ...                   ...                ...                 ...
62958       ...                     0                  0                   0
62959       ...                     0                  0                   0
62960       ...                     0                  0                   0
62961       ...                     0                  0                   0
62962       ...                     0                  0                   0
62963       ...                     0                  0                   0
62964       ...                     0                  0                   0
62965       ...                     0                  0                   0
62966       ...                     0                  0                   0
62967       ...                     0                  0                   0
62968       ...                     0                  0                   0
62969       ...                     0                  0                   0
62970       ...                     0                  0                   0
62971       ...                   134                134                 134
62972       ...                 20679              20679               12707
62973       ...                     0                  0                   0
62974       ...                   500                500                 500
62975       ...                     0                  0                   0
62976       ...                     0                  0                   0
62977       ...                     0                  0                   0
62978       ...                     0                  0                   0
62979       ...                     0                  0                   0
62980       ...                     0                  0                   0
62981       ...                     0                  0                   0
62982       ...                     0                  0                   0
62983       ...                 12318              12318               12123
62984       ...                106972             106972               56506
62985       ...                     0                  0                   0
62986       ...                     0                  0                   0
62987       ...                     0                  0                   0

       Points_Sum  L1Y_Points_Sum  Ration_L1Y_Flight_Count  \
0          619760          370211                 0.509524
1          415768          238410                 0.514286
2          406361          233798                 0.518519
3          372204          186100                 0.434783
4          338813          210365                 0.532895
5          343121          152538                 0.456522
6          298873          175673                 0.504950
7          351198          193601                 0.589041
8          295158          168028                 0.410714
9          251907          143958                 0.390625
10         337839          197445                 0.534884
11         353101          231452                 0.606897
12         245808          156214                 0.517241
13         270704          158779                 0.559322
14         328345          186491                 0.500000
15         310002          143671                 0.500000
16         257193          151717                 0.544554
17         281705          137196                 0.625000
18         249914          139498                 0.500000
19         215694          116995                 0.473684
20         251134          176428                 0.584906
21         286520          188808                 0.652174
22         277394          188661                 0.542553
23         280760          127944                 0.350000
24         235939          160312                 0.613636
25         274882          152718                 0.677419
26         795398          474610                 0.446009
27         235176          119623                 0.459459
28         237787          143047                 0.514851
29         224081          137148                 0.517241
...           ...             ...                      ...
62958         700             200                 0.500000
62959           0               0                 1.000000
62960           0               0                 1.000000
62961         400               0                 0.000000
62962         400               0                 0.000000
62963         400             400                 1.000000
62964         400               0                 0.000000
62965         400               0                 0.000000
62966         400               0                 0.000000
62967           0               0                 0.000000
62968           0               0                 0.000000
62969           0               0                 0.000000
62970           0               0                 0.000000
62971         134             134                 1.000000
62972       20679           12707                 1.000000
62973           0               0                 1.000000
62974         900             900                 1.000000
62975         400             400                 1.000000
62976         213               0                 0.500000
62977           0               0                 0.000000
62978           0               0                 1.000000
62979           0               0                 0.000000
62980           0               0                 0.000000
62981           0               0                 1.000000
62982           0               0                 0.000000
62983       12318           12123                 1.000000
62984      106972           56506                 1.000000
62985           0               0                 1.000000
62986           0               0                 0.000000
62987           0               0                 0.000000

       Ration_P1Y_Flight_Count  Ration_P1Y_BPS Ration_L1Y_BPS  Point_NotFlight
0                     0.490476        0.487221       0.512777               50
1                     0.485714        0.489289       0.510708               33
2                     0.481481        0.481467       0.518530               26
3                     0.565217        0.551722       0.448275               12
4                     0.467105        0.469054       0.530943               39
5                     0.543478        0.608233       0.391764               15
6                     0.495050        0.495048       0.504948               29
7                     0.410959        0.522078       0.477919               14
8                     0.589286        0.483459       0.516537                7
9                     0.609375        0.526951       0.473044               16
10                    0.465116        0.470612       0.529384                3
11                    0.393103        0.396882       0.603114               66
12                    0.482759        0.426090       0.573905                4
13                    0.440678        0.452211       0.547785               20
14                    0.500000        0.487910       0.512086               12
15                    0.500000        0.581242       0.418755                8
16                    0.455446        0.479445       0.520550               22
17                    0.375000        0.578307       0.421689               13
18                    0.500000        0.513529       0.486466               23
19                    0.526316        0.516643       0.483352                3
20                    0.415094        0.338585       0.661411                9
21                    0.347826        0.382324       0.617672                9
22                    0.457447        0.371243       0.628752               46
23                    0.650000        0.596150       0.403846                9
24                    0.386364        0.369269       0.630726               12
25                    0.322581        0.503740       0.496256               10
26                    0.553991        0.586837       0.413158               49
27                    0.540541        0.537107       0.462888               14
28                    0.485149        0.435550       0.564445               11
29                    0.482759        0.426068       0.573927               15
...                        ...             ...            ...              ...
62958                 0.500000        0.713267       0.285307                0
62959                 0.000000        0.000000       0.000000                0
62960                 0.000000        0.000000       0.000000                0
62961                 1.000000        0.997506       0.000000                0
62962                 1.000000        0.997506       0.000000                0
62963                 0.000000        0.000000       0.997506                0
62964                 1.000000        0.997506       0.000000                0
62965                 1.000000        0.997506       0.000000                0
62966                 1.000000        0.997506       0.000000                0
62967                 1.000000        0.000000       0.000000                0

In [6]:
explore = data.describe(percentiles=[], include="all").T #。T表示转置
print(explore)
explore["null"] = len(data)-explore['count'] #计算非空
explore = explore[["null", "max", "min"]]
explore.to_excel("dataexplore.xls")

                         count unique         top   freq      mean       std  \
MEMBER_NO                62988    NaN         NaN    NaN   31494.5   18183.2
FFP_DATE                 62988   3068  2011/01/13    184       NaN       NaN
FIRST_FLIGHT_DATE        62988   3406  2013/02/16     96       NaN       NaN
GENDER                   62985      2           男  48134       NaN       NaN
FFP_TIER                 62988    NaN         NaN    NaN   4.10216  0.373856
WORK_CITY                60719   3310          广州   9385       NaN       NaN
WORK_PROVINCE            59740   1185          广东  17507       NaN       NaN
WORK_COUNTRY             62962    118          CN  57748       NaN       NaN
AGE                      62568    NaN         NaN    NaN   42.4763   9.88591
LOAD_TIME                62988      1  2014/03/31  62988       NaN       NaN
FLIGHT_COUNT             62988    NaN         NaN    NaN   11.8394   14.0495
BP_SUM                   62988    NaN         NaN    NaN   10925.1   16339.5
EP_SUM_YR_1              62988    NaN         NaN    NaN         0         0
EP_SUM_YR_2              62988    NaN         NaN    NaN    265.69    1645.7
SUM_YR_1                 62437    NaN         NaN    NaN   5355.38   8109.45
SUM_YR_2                 62850    NaN         NaN    NaN   5604.03   8703.36
SEG_KM_SUM               62988    NaN         NaN    NaN   17123.9   20960.8
WEIGHTED_SEG_KM          62988    NaN         NaN    NaN   12777.2   17578.6
LAST_FLIGHT_DATE         62988    731  2014/03/31    959       NaN       NaN
AVG_FLIGHT_COUNT         62988    NaN         NaN    NaN   1.54215     1.787
AVG_BP_SUM               62988    NaN         NaN    NaN   1421.44   2083.12
BEGIN_TO_FIRST           62988    NaN         NaN    NaN   120.145   159.573
LAST_TO_END              62988    NaN         NaN    NaN    176.12   183.822
AVG_INTERVAL             62988    NaN         NaN    NaN   67.7498   77.5179
MAX_INTERVAL             62988    NaN         NaN    NaN   166.034   123.397
ADD_POINTS_SUM_YR_1      62988    NaN         NaN    NaN   540.317   3956.08
ADD_POINTS_SUM_YR_2      62988    NaN         NaN    NaN   814.689    5121.8
EXCHANGE_COUNT           62988    NaN         NaN    NaN  0.319775     1.136
avg_discount             62988    NaN         NaN    NaN  0.721558  0.185427
P1Y_Flight_Count         62988    NaN         NaN    NaN   5.76626   7.21092
L1Y_Flight_Count         62988    NaN         NaN    NaN   6.07316   8.17513
P1Y_BP_SUM               62988    NaN         NaN    NaN   5366.72   8537.77
L1Y_BP_SUM               62988    NaN         NaN    NaN   5558.36   9351.96
EP_SUM                   62988    NaN         NaN    NaN    265.69    1645.7
ADD_Point_SUM            62988    NaN         NaN    NaN   1355.01   7868.48
Eli_Add_Point_Sum        62988    NaN         NaN    NaN    1620.7    8294.4
L1Y_ELi_Add_Points       62988    NaN         NaN    NaN   1080.38   5639.86
Points_Sum               62988    NaN         NaN    NaN   12545.8   20507.8
L1Y_Points_Sum           62988    NaN         NaN    NaN   6638.74   12601.8
Ration_L1Y_Flight_Count  62988    NaN         NaN    NaN  0.486419  0.319105
Ration_P1Y_Flight_Count  62988    NaN         NaN    NaN  0.513581  0.319105
Ration_P1Y_BPS           62988    NaN         NaN    NaN  0.522293  0.339632
Ration_L1Y_BPS           62988    NaN         NaN    NaN  0.468422  0.338956
Point_NotFlight          62988    NaN         NaN    NaN   2.72815   7.36416

                          min       50%       max
MEMBER_NO                   1   31494.5     62988
FFP_DATE                  NaN       NaN       NaN
FIRST_FLIGHT_DATE         NaN       NaN       NaN
GENDER                    NaN       NaN       NaN
FFP_TIER                    4         4         6
WORK_CITY                 NaN       NaN       NaN
WORK_PROVINCE             NaN       NaN       NaN
WORK_COUNTRY              NaN       NaN       NaN
AGE                         6        41       110
LOAD_TIME                 NaN       NaN       NaN
FLIGHT_COUNT                2         7       213
BP_SUM                      0      5700    505308
EP_SUM_YR_1                 0         0         0
EP_SUM_YR_2                 0         0     74460
SUM_YR_1                    0      2800    239560
SUM_YR_2                    0      2773    234188
SEG_KM_SUM                368      9994    580717
WEIGHTED_SEG_KM             0   6978.26    558440
LAST_FLIGHT_DATE          NaN       NaN       NaN
AVG_FLIGHT_COUNT         0.25     0.875    26.625
AVG_BP_SUM                  0   752.375   63163.5
BEGIN_TO_FIRST              0        50       729
LAST_TO_END                 1       108       731
AVG_INTERVAL                0   44.6667       728
MAX_INTERVAL                0       143       728
ADD_POINTS_SUM_YR_1         0         0    600000
ADD_POINTS_SUM_YR_2         0         0    728282
EXCHANGE_COUNT              0         0        46
avg_discount                0  0.711856       1.5
P1Y_Flight_Count            0         3       118
L1Y_Flight_Count            0         3       111
P1Y_BP_SUM                  0      2692    246197
L1Y_BP_SUM                  0      2547    259111
EP_SUM                      0         0     74460
ADD_Point_SUM               0         0    984938
Eli_Add_Point_Sum           0         0    984938
L1Y_ELi_Add_Points          0         0    728282
Points_Sum                  0    6328.5    985572
L1Y_Points_Sum              0    2860.5    728282
Ration_L1Y_Flight_Count     0       0.5         1
Ration_P1Y_Flight_Count     0       0.5         1
Ration_P1Y_BPS              0  0.514252  0.999989
Ration_L1Y_BPS              0  0.476747  0.999993
Point_NotFlight             0         0       140

In [2]:
# 数据清洗
import pandas as pd
datapath = "air_data.csv"
data = pd.read_csv(datapath,encoding="utf-8")
data = data[data["SUM_YR_1"].notnull()*data["SUM_YR_2"].notnull()]#保留两个都不为空的数据
index1 = data["SUM_YR_1"] != 0
index2 = data["SUM_YR_2"] != 0
index3 = (data["SEG_KM_SUM"]==0) & (data["avg_discount"]==0)
data = data[index1 | index2 | index3]
data.to_excel("cleancsv.xls")

e:\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:179: UserWarning: evaluating in Python space because the '*' operator is not supported by numexpr for the bool dtype, use '&' instead
  .format(op=op_str, alt_op=unsupported[op_str]))

In [5]:
# 数据标准化
import pandas as pd
inputdatafile = "zscoredata.xls"
outdatafile = "zscoredata_new.xls"
data = pd.read_excel(inputdatafile)
data = (data-data.mean(axis=0))/(data.std(axis=0)) #标准差的转换
data.columns = ["Z"+i for i in data.columns]
print("-----------------------------------------")
print(data)
data.to_excel(outdatafile)

-----------------------------------------
             ZL        ZR        ZF        ZM        ZC
0      1.689882  0.140299 -0.635788  0.068794 -0.337186
1      1.689882 -0.322442  0.852453  0.843848 -0.553613
2      1.681743 -0.487707 -0.210576  0.158569 -1.094680
3      1.534185 -0.785184  0.002030  0.273091 -1.148787
4      0.890167 -0.426559 -0.635788 -0.685170  1.231909
5     -0.232618 -0.690983 -0.635788 -0.603898 -0.391293
6     -0.496949  1.996225 -0.706656 -0.661752 -1.311107
7     -0.868498 -0.267905 -0.281445 -0.262422  3.396178
8     -1.074796  0.024614 -0.423182 -0.520916  0.149775
9      1.907150 -0.884343  2.978512  2.130285  0.366201
10     0.477571 -0.565382  0.852453 -0.067815 -0.661826
11     0.469078 -0.938881  0.072898  0.104277 -0.012546
12     0.469078 -0.185273 -0.139707 -0.220194 -0.932360
13     0.452801  1.516957  0.072898 -0.300659  3.287964
14     0.368937  0.746822 -0.635788 -0.626270 -0.283079
15     0.312320 -0.895912  0.498110  0.954428 -0.499506
16    -0.026320 -0.681067  0.072898  0.324628  0.366201
17    -0.051090  2.723391 -0.635788 -0.748725  0.799055
18    -0.092137  2.878740 -0.706656 -0.733952 -0.661826
19    -0.150170 -0.520760  1.277665  1.391711  1.123696
20    -0.438916 -0.195188 -0.564919 -0.442826 -0.770040
21     0.866813  1.169900 -0.352313 -0.191125 -1.311107
22    -0.728017 -0.509192 -0.423182 -0.243564 -0.120759
23    -0.818958  1.731801 -0.706656 -0.729202  0.041561
24     1.764192 -0.190231 -0.706656 -0.684410 -0.174866
25     0.182455  2.531684 -0.564919 -0.505288 -0.986467
26     0.148485  0.135342 -0.706656 -0.745352  1.015482
27     0.141408 -0.735605  0.852453  0.747756 -0.932360
28     0.132915 -0.069587 -0.635788 -0.544903 -1.635747
29     0.132915 -0.933923 -0.635788 -0.634250 -2.339135
...         ...       ...       ...       ...       ...
62014  0.768795 -0.823195 -0.139707  0.183269 -0.499506
62015  0.785426 -0.889301  1.135928  2.066493 -0.607720
62016  0.759241 -0.393506  0.568979  0.382055 -0.283079
62017  0.752163 -0.140651 -0.139707  0.200701 -0.878253
62018  0.735886 -0.884343 -0.352313 -0.254727 -0.553613
62019  0.739425 -0.537287  1.206796  0.661354 -0.391293
62020  0.748625 -0.735605  2.057220  3.103935  0.149775
62021  0.714655 -0.905828  2.624169  3.719010  0.149775
62022  0.711116 -0.334011  0.781585  1.437975  3.774925
62023  0.694485 -0.223283  0.356373  1.129084 -0.066652
62024  0.674315 -0.867817 -0.564919 -0.420834 -0.986467
62025  0.603544  0.107246 -0.352313 -0.415799 -0.174866
62026  0.674315 -0.565382 -0.068839  0.027232 -0.283079
62027  0.606021 -0.343927 -0.706656 -0.619810 -0.174866
62028  0.660161 -0.459612 -0.564919 -0.477596 -0.878253
62029  0.642468 -0.393506  0.002030  0.005524  0.366201
62030  0.667238 -0.053061  0.002030 -0.139350 -0.066652
62031  0.635391  0.107246 -0.706656 -0.525713 -0.661826
62032  0.621237  1.209564 -0.635788 -0.447813 -1.094680
62033  0.621237  0.657579  0.143767  0.669096 -0.391293
62034  0.635391 -0.201799 -0.635788 -0.596440 -0.553613
62035  0.602482 -0.537287  0.639847  1.042017 -0.986467
62036  0.601421  0.487356 -0.281445  0.100904 -0.607720
62037  0.612036  0.046098 -0.494051 -0.183050 -0.066652
62038  0.587266 -0.740563 -0.564919 -0.331676  0.961375
62039  0.590805 -0.938881  1.986351  2.694820 -0.499506
62040  0.578774 -0.086114  0.072898  0.163414  0.366201
62041  0.592928 -0.796753  0.710716  1.607265 -0.932360
62042  0.575235 -0.211715 -0.423182 -0.187230 -0.661826
62043  0.529234 -0.376980  0.143767  0.616752  0.041561

[62044 rows x 5 columns]