In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
data_train = pd.read_table(r"./horseColicTraining.txt", header=None)
data_test = pd.read_table(r"./horseColicTest.txt", header=None)
display(data_train.head(), data_test.head())

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,2.0,1.0,38.5,66.0,28.0,3.0,3.0,0.0,2.0,5.0,...,0.0,0.0,0.0,3.0,5.0,45.0,8.4,0.0,0.0,0.0
1,1.0,1.0,39.2,88.0,20.0,0.0,0.0,4.0,1.0,3.0,...,0.0,0.0,0.0,4.0,2.0,50.0,85.0,2.0,2.0,0.0
2,2.0,1.0,38.3,40.0,24.0,1.0,1.0,3.0,1.0,3.0,...,0.0,0.0,0.0,1.0,1.0,33.0,6.7,0.0,0.0,1.0
3,1.0,9.0,39.1,164.0,84.0,4.0,1.0,6.0,2.0,2.0,...,1.0,2.0,5.0,3.0,0.0,48.0,7.2,3.0,5.3,0.0
4,2.0,1.0,37.3,104.0,35.0,0.0,0.0,6.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,74.0,7.4,0.0,0.0,0.0

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,2,1,38.5,54,20,0,1,2,2,3,...,2,2,5.9,0,2,42.0,6.3,0,0.0,1
1,2,1,37.6,48,36,0,0,1,1,0,...,0,0,0.0,0,0,44.0,6.3,1,5.0,1
2,1,1,37.7,44,28,0,4,3,2,5,...,1,1,0.0,3,5,45.0,70.0,3,2.0,1
3,1,1,37.0,56,24,3,1,4,2,4,...,1,1,0.0,0,0,35.0,61.0,3,2.0,0
4,2,1,38.0,42,12,3,0,3,1,1,...,0,0,0.0,0,2,37.0,5.8,0,0.0,1

In [3]:
# 得到训练和测试数据集
x_train = data_train.iloc[:,:-1]
y_train = data_train[21]
x_test = data_test.iloc[:,:-1]
y_test = data_test[21]

In [4]:
# 建立、训练、测试模型
clf = LogisticRegression()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.7313432835820896

In [5]:
import sklearn
from sklearn import datasets, linear_model
from sklearn import metrics
from sklearn import tree
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.grid_search import GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_predict
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import BernoulliRBM
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.externals import joblib

In [6]:
# 线性回归算法，最小二乘法，函数名 LinearRegression
def mx_line(train_x, train_y):
    mx = LinearRegression()
    mx.fit(train_x, train_y)
    return mx

# 逻辑回归算法，函数名, LogisticRegression
def mx_log(train_x, train_y):
#     mx = LogisticRegression(penalty='12')
    mx = LogisticRegression()
    mx.fit(train_x, train_y)
    return mx

# 多项式朴素贝叶斯算法，Multinomial Naive Bayes，函数名，multinomialnb
def mx_bayes(train_x, train_y):
    mx = MultinomialNB(alpha=0.01)
    mx.fit(train_x, train_y)
    return mx
mx = mx_bayes(x_train, y_train)
mx.score(x_test, y_test)

# KNN近邻算法，函数名，KNeighborsClassifier
def mx_knn(train_x, train_y):
    mx = KNeighborsClassifier()
    mx.fit(train_x, train_y)
    return mx

# 随机随机森林算法,random forest classifier，函数名,RandomForestClassifier
def mx_forest(train_x, train_y):
    mx = RandomForestClassifier(n_estimators=8)
    mx.fit(train_x, train_y)
    return mx

# 决策树方法
def mx_dtree(train_x, train_y):
    mx = tree.DecisionTreeClassifier()
    mx.fit(train_x, train_y)
    return mx

# GBDT迭代决策树算法，Gradient Boosting Decision Tree,
# 又叫MART(Multiple Additive Regression Tree)，函数名，GradientBoostingClassifier
def mx_GBDT(train_x, train_y):
    mx = GradientBoostingClassifier(n_estimators=200)
    mx.fit(train_x, train_y)
    return mx

# SVM向量机算法，函数名 SVC
def mx_svm(train_x, train_y):
    mx = SVC(kernel='rbf', probability=True)
    mx.fit(train_x, train_y)
    return mx

# SVM-cross向量机交叉算法，函数名 SVC，自动调优
def mx_svm_cross(train_x, train_y):
    mx = SVC(kernel='rbf', probability=True)
    param_grid = {'C':[1e-3, 1e-2, 1e-1, 1, 10, 100, 1000], 'gamma':[0.001, 0.0001]}
    grid_search = GridSearchCV(mx, param_grid, n_jobs=1, verbose=1)
    grid_search.fit(train_x, train_y)
    best_parameters = grid_search.best_estimator_.get_params()
    mx = SVC(kernel='rbf', C=best_parameters['C'], gamma=best_parameters['gamma'], probability=True)
    mx.fit(train_x, train_y)
    return mx

# MLP神经网络算法
def mx_MLP(train_x, train_y):
    # mx = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5,2), random_state=1)
    mx = MLPClassifier()
    mx.fit(train_x, train_y)
    return mx

# 神经网络回归算法
def mx_MLP_reg(train_x, train_y):
    # mx = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5,2), random_state=1)
    mx = MLPRegressor()
    mx.fit(train_x, train_y)
    return mx

In [7]:
mxfunSgn = {'line': mx_line,
            'log': mx_log,
            'bayes': mx_bayes,
            'knn': mx_knn,
            'forest': mx_forest,
            'dtree': mx_dtree,
            'gbdt': mx_GBDT,
            'svm': mx_svm,
            'svmcr': mx_svm_cross,
            'mlp': mx_MLP,
            'mlppreg': mx_MLP_reg}

In [10]:
resultlist = {}
for k in mxfunSgn:
    mx = mxfunSgn[k](x_train, y_train)
    score = mx.score(x_test, y_test)
    print(k, score)
    resultlist[k] = score
# resultlist.values.max()

line 0.0689157155044412
log 0.7313432835820896
bayes 0.4925373134328358
knn 0.7164179104477612
forest 0.7164179104477612
dtree 0.6865671641791045
gbdt 0.746268656716418
svm 0.7164179104477612
Fitting 3 folds for each of 14 candidates, totalling 42 fits

[Parallel(n_jobs=1)]: Done  42 out of  42 | elapsed:    1.5s finished

svmcr 0.7761194029850746
mlp 0.6865671641791045
mlppreg -0.6862824835491379

In [12]:
sorted(resultlist, key=lambda x:resultlist[x])[-1]

'svmcr'

In [13]:
resultlist["svmcr"]

0.7761194029850746